/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const Feature = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
  'included' : IDL.Bool,
});
export const Variant = IDL.Record({
  'id' : IDL.Nat,
  'features' : IDL.Vec(Feature),
  'name' : IDL.Text,
  'productId' : IDL.Nat,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Product],
      [],
    ),
  'addVariant' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Vec(Feature)],
      [Variant],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deleteVariant' : IDL.Func([IDL.Nat], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getVariant' : IDL.Func([IDL.Nat], [Variant], ['query']),
  'getVariantsByProductId' : IDL.Func([IDL.Nat], [IDL.Vec(Variant)], ['query']),
  'seedData' : IDL.Func([], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Product],
      [],
    ),
  'updateVariant' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Float64, IDL.Vec(Feature)],
      [Variant],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const Feature = IDL.Record({
    'value' : IDL.Text,
    'name' : IDL.Text,
    'included' : IDL.Bool,
  });
  const Variant = IDL.Record({
    'id' : IDL.Nat,
    'features' : IDL.Vec(Feature),
    'name' : IDL.Text,
    'productId' : IDL.Nat,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Product],
        [],
      ),
    'addVariant' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Vec(Feature)],
        [Variant],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deleteVariant' : IDL.Func([IDL.Nat], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getVariant' : IDL.Func([IDL.Nat], [Variant], ['query']),
    'getVariantsByProductId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Variant)],
        ['query'],
      ),
    'seedData' : IDL.Func([], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Product],
        [],
      ),
    'updateVariant' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Float64, IDL.Vec(Feature)],
        [Variant],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };