/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CarCategory = { 'mpv' : null } |
  { 'suv' : null } |
  { 'coupe' : null } |
  { 'sedan' : null } |
  { 'hatchback' : null };
export interface CarModel {
  'id' : bigint,
  'tagline' : string,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : CarCategory,
}
export interface Feature {
  'value' : string,
  'name' : string,
  'included' : boolean,
}
export interface Trim {
  'id' : bigint,
  'features' : Array<Feature>,
  'name' : string,
  'carModelId' : bigint,
  'price' : number,
  'monthlyEMI' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCarModel' : ActorMethod<
    [string, string, CarCategory, string, string],
    CarModel
  >,
  'addTrim' : ActorMethod<
    [bigint, string, number, number, Array<Feature>],
    Trim
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimAdminIfNoneExists' : ActorMethod<[], boolean>,
  'deleteCarModel' : ActorMethod<[bigint], undefined>,
  'deleteTrim' : ActorMethod<[bigint], undefined>,
  'getAllCarModels' : ActorMethod<[], Array<CarModel>>,
  'getCallerPrincipal' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCarModel' : ActorMethod<[bigint], CarModel>,
  'getNextCarModelId' : ActorMethod<[], bigint>,
  'getNextTrimId' : ActorMethod<[], bigint>,
  'getTrim' : ActorMethod<[bigint], Trim>,
  'getTrimsByCarModelId' : ActorMethod<[bigint], Array<Trim>>,
  'getTrimsByIds' : ActorMethod<[Array<bigint>], Array<Trim>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isSeeded' : ActorMethod<[], boolean>,
  'resetAdmin' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedData' : ActorMethod<[], undefined>,
  'updateCarModel' : ActorMethod<
    [bigint, string, string, CarCategory, string, string],
    CarModel
  >,
  'updateTrim' : ActorMethod<
    [bigint, bigint, string, number, number, Array<Feature>],
    Trim
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];