/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Feature {
  'value' : string,
  'name' : string,
  'included' : boolean,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
}
export interface Variant {
  'id' : bigint,
  'features' : Array<Feature>,
  'name' : string,
  'productId' : bigint,
  'price' : number,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<[string, string, string, string], Product>,
  'addVariant' : ActorMethod<[bigint, string, number, Array<Feature>], Variant>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteVariant' : ActorMethod<[bigint], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getVariant' : ActorMethod<[bigint], Variant>,
  'getVariantsByProductId' : ActorMethod<[bigint], Array<Variant>>,
  'seedData' : ActorMethod<[], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, string, string],
    Product
  >,
  'updateVariant' : ActorMethod<
    [bigint, bigint, string, number, Array<Feature>],
    Variant
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];