/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CarModel {
    id: bigint;
    tagline: string;
    name: string;
    description: string;
    imageUrl: string;
    category: CarCategory;
}
export interface Trim {
    id: bigint;
    features: Array<Feature>;
    name: string;
    carModelId: bigint;
    price: number;
    monthlyEMI: number;
}
export interface Feature {
    value: string;
    name: string;
    included: boolean;
}
export interface UserProfile {
    name: string;
}
export enum CarCategory {
    mpv = "mpv",
    suv = "suv",
    coupe = "coupe",
    sedan = "sedan",
    hatchback = "hatchback"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCarModel(name: string, description: string, category: CarCategory, tagline: string, imageUrl: string): Promise<CarModel>;
    addTrim(carModelId: bigint, name: string, price: number, monthlyEMI: number, features: Array<Feature>): Promise<Trim>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    claimAdminIfNoneExists(): Promise<boolean>;
    deleteCarModel(id: bigint): Promise<void>;
    deleteTrim(id: bigint): Promise<void>;
    getAllCarModels(): Promise<Array<CarModel>>;
    getCallerPrincipal(): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCarModel(id: bigint): Promise<CarModel>;
    getNextCarModelId(): Promise<bigint>;
    getNextTrimId(): Promise<bigint>;
    getTrim(id: bigint): Promise<Trim>;
    getTrimsByCarModelId(carModelId: bigint): Promise<Array<Trim>>;
    getTrimsByIds(trimIds: Array<bigint>): Promise<Array<Trim>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isSeeded(): Promise<boolean>;
    resetAdmin(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedData(): Promise<void>;
    updateCarModel(id: bigint, name: string, description: string, category: CarCategory, tagline: string, imageUrl: string): Promise<CarModel>;
    updateTrim(id: bigint, carModelId: bigint, name: string, price: number, monthlyEMI: number, features: Array<Feature>): Promise<Trim>;
}
import type { CarCategory as _CarCategory, CarModel as _CarModel, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCarModel(arg0: string, arg1: string, arg2: CarCategory, arg3: string, arg4: string): Promise<CarModel> {
        if (this.processError) {
            try {
                const result = await this.actor.addCarModel(arg0, arg1, to_candid_CarCategory_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return from_candid_CarModel_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCarModel(arg0, arg1, to_candid_CarCategory_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return from_candid_CarModel_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async addTrim(arg0: bigint, arg1: string, arg2: number, arg3: number, arg4: Array<Feature>): Promise<Trim> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrim(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrim(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimAdminIfNoneExists(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAdminIfNoneExists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAdminIfNoneExists();
            return result;
        }
    }
    async deleteCarModel(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCarModel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCarModel(arg0);
            return result;
        }
    }
    async deleteTrim(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrim(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrim(arg0);
            return result;
        }
    }
    async getAllCarModels(): Promise<Array<CarModel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCarModels();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCarModels();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerPrincipal(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPrincipal();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCarModel(arg0: bigint): Promise<CarModel> {
        if (this.processError) {
            try {
                const result = await this.actor.getCarModel(arg0);
                return from_candid_CarModel_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCarModel(arg0);
            return from_candid_CarModel_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNextCarModelId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextCarModelId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextCarModelId();
            return result;
        }
    }
    async getNextTrimId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextTrimId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextTrimId();
            return result;
        }
    }
    async getTrim(arg0: bigint): Promise<Trim> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrim(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrim(arg0);
            return result;
        }
    }
    async getTrimsByCarModelId(arg0: bigint): Promise<Array<Trim>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrimsByCarModelId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrimsByCarModelId(arg0);
            return result;
        }
    }
    async getTrimsByIds(arg0: Array<bigint>): Promise<Array<Trim>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrimsByIds(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrimsByIds(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isSeeded(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isSeeded();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isSeeded();
            return result;
        }
    }
    async resetAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async seedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedData();
            return result;
        }
    }
    async updateCarModel(arg0: bigint, arg1: string, arg2: string, arg3: CarCategory, arg4: string, arg5: string): Promise<CarModel> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCarModel(arg0, arg1, arg2, to_candid_CarCategory_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return from_candid_CarModel_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCarModel(arg0, arg1, arg2, to_candid_CarCategory_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return from_candid_CarModel_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTrim(arg0: bigint, arg1: bigint, arg2: string, arg3: number, arg4: number, arg5: Array<Feature>): Promise<Trim> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrim(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrim(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_CarCategory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CarCategory): CarCategory {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_CarModel_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CarModel): CarModel {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    tagline: string;
    name: string;
    description: string;
    imageUrl: string;
    category: _CarCategory;
}): {
    id: bigint;
    tagline: string;
    name: string;
    description: string;
    imageUrl: string;
    category: CarCategory;
} {
    return {
        id: value.id,
        tagline: value.tagline,
        name: value.name,
        description: value.description,
        imageUrl: value.imageUrl,
        category: from_candid_CarCategory_n5(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mpv: null;
} | {
    suv: null;
} | {
    coupe: null;
} | {
    sedan: null;
} | {
    hatchback: null;
}): CarCategory {
    return "mpv" in value ? CarCategory.mpv : "suv" in value ? CarCategory.suv : "coupe" in value ? CarCategory.coupe : "sedan" in value ? CarCategory.sedan : "hatchback" in value ? CarCategory.hatchback : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CarModel>): Array<CarModel> {
    return value.map((x)=>from_candid_CarModel_n3(_uploadFile, _downloadFile, x));
}
function to_candid_CarCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CarCategory): _CarCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CarCategory): {
    mpv: null;
} | {
    suv: null;
} | {
    coupe: null;
} | {
    sedan: null;
} | {
    hatchback: null;
} {
    return value == CarCategory.mpv ? {
        mpv: null
    } : value == CarCategory.suv ? {
        suv: null
    } : value == CarCategory.coupe ? {
        coupe: null
    } : value == CarCategory.sedan ? {
        sedan: null
    } : value == CarCategory.hatchback ? {
        hatchback: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
